version: "3"
services:
  unleash-db:
    expose:
      - "5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:10-alpine

  unleash:
    image: unleashorg/unleash-server:3.1
    ports:
      - "4242:4242"
    environment:
      DATABASE_URL: postgres://postgres:unleash@unleash-db/postgres
    depends_on:
      - unleash-db
    command: >
      sh -c "
        while ! nc -z unleash-db 5432; do
          echo 'Postgres is unavailable.'
          sleep 1
        done
        npm run start"