apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-brevdata
  namespace: default
  labels:
    team: pensjonpersondialog
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: "/api/brevdata/isAlive"
    initialDelay: 3
    timeout: 1
  ingresses:
    - https://pensjon-brevdata.prod.nais.adeo.no
  readiness:
    path: "/api/brevdata/isReady"
    initialDelay: 3
    timeout: 1
