apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-brevdata
  namespace: default
  labels:
    team: pensjonsbrev
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
  liveness:
    path: "/api/internal/isAlive"
    initialDelay: 35
    timeout: 3
  ingresses:
    - https://pensjon-brevdata.nais.preprod.local
  readiness:
    path: "/api/internal/isReady"
    initialDelay: 35
    timeout: 3
  prometheus:
    enabled: true
    path: "/api/internal/prometheus"
  env:
    - name: UNLEASH_ENDPOINT_URL
      value: https://unleash.nais.adeo.no/api/