apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ application }}
  namespace: pensjonsbrev
  labels:
    team: pensjonsbrev
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: {{ replicas.min }}
    max: {{ replicas.max }}
  liveness:
    path: "/api/internal/isAlive"
    initialDelay: 35
    timeout: 3
  ingresses:
    {{#each ingresses as |url|}}
       - {{url}}
      {{/each}}
  readiness:
    path: "/api/internal/isReady"
    initialDelay: 35
    timeout: 3
  prometheus:
    enabled: true
    path: "/api/internal/prometheus"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  envFrom:
    - secret: {{ application }}-unleash-api-token
  env:
    - name: ENVIRONMENT_NAME
      value: {{ environmentname }}
  accessPolicy:
    inbound:
      rules:
        {{#each inboundRules as |app|}}
            - application: {{app.name }}
              namespace: {{app.namespace}}
              cluster: {{app.cluster}}
        {{/each}}
    outbound:
      external:
        - host: teampensjon-unleash-api.nav.cloud.nais.io