# TODO: PL-5232 - Slett når de nye gcp deploymentene fungerer for pesys
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-brevmetadata
  namespace: pensjonsbrev
  labels:
    team: pensjonsbrev
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 2
  liveness:
    path: "/api/internal/isAlive"
    initialDelay: 35
    timeout: 3
  ingresses:
    - https://pensjon-brevmetadata-pensjonsbrev.nais.adeo.no
  readiness:
    path: "/api/internal/isReady"
    initialDelay: 35
    timeout: 3
  prometheus:
    enabled: true
    path: "/api/internal/prometheus"
  env:
    - name: UNLEASH_ENDPOINT_URL
      value: https://unleash.nais.io/api/