# TODO: PL-5232 - Slett når de nye gcp deploymentene fungerer for pesys
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ application }}
  namespace: pensjonsbrev
  labels:
    team: pensjonsbrev
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
  liveness:
    path: "/api/internal/isAlive"
    initialDelay: 35
    timeout: 3
  ingresses:
    - {{ ingress }}
  readiness:
    path: "/api/internal/isReady"
    initialDelay: 35
    timeout: 3
  prometheus:
    enabled: true
    path: "/api/internal/prometheus"
  env:
    - name: UNLEASH_ENDPOINT_URL
      value: {{ unleashurl }}
    - name: ENVIRONMENT_NAME
      value: {{ environmentname }}