application: "pensjon-brevmetadata"
ingresses:
  - "https://pensjon-brevmetadata.intern.nav.no"
environmentname: "prod"
replicas:
  min: 2
  max: 2
inboundRules:
  - name: pensjon-pen
    namespace: pensjondeployer
    cluster: prod-fss
  - name: pensjon-psak
    namespace: pensjondeployer
    cluster: prod-fss
  - name: skribenten-backend
    namespace: pensjonsbrev
    cluster: prod-gcp
