apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: {{ application }}
  namespace: pensjonsbrev
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: teampensjon
  secretName: {{ application }}-unleash-api-token

  # Specify which environment the API token should be created for.
  # Can be one of: development, or production.
  environment: {{ unleashEnvironment }}
