== Pensjon Brevdata Mapper

Mapping av brev og vedlegg.

=== BrevdataMapper

BrevdataMapper inneholder alle brevene i pesys.

Utgangspunktet er generert basert på PEN databasen hvor det er kjørt et script som kopierer over kolonner og tabeller som er relevant for å bygge opp et brev.

IMPORTANT: Når applikasjonen er produksjonsatt og i full bruk, vil det ikke være nødvendig å kjøre databsescriptet igjen.
Scriptet er kun brukt for å gi et utgangspunkt for applikasjonen slik at innholdet er det samme som i PEN databasen.

For å legge til et nytt brev må det legges til en ny mapping med følgende elementer basert på det er et doksysbrev eller et gammeltbrev(hpextream brev).

.Brev
[#brev-tabell,cols="1,1,3",]
|===
|Element |Type |Beskrivelse

|brevkodeInBrevsystem
|String
|Inneholder brevkoden som blir brukt av pesys.

|redigerbart
|boolean
|Inneholder verdi for om brevet er redigerbart eller ikke

|dekode
|String
|Inneholder en kort beskrivelse av brevet

|brevkategori
|BrevkategoriCode
|Inneholder brevkategorien

|doktype
|DokumenttypeCode
|Inneholder dokumenttypen: inngående, utgående eller notat

|sprak
|List<SprakCode>
|Inneholder liste med hvilke språk brevet støtter

|visIPselv
|Boolean
|Inneholder verdi om brevet skal vises i Pselv

|utland
|BrevUtlandCode
|Inneholder kode for når brevet skal vises: Utland, nasjonalt, alltid

|brevregeltype
|BrevregeltypeCode
|Inneholder verdi for brevregeltype

|dokumentkategori
|DokumentkategoriCode
|Inneholder dokumentkategorikode for brevet

|synligForVeileder
|Boolean
|Inneholder verdi om brevet skal være synlig for veileder

|brevkontekst
|BrevkontekstCode
|Inneholder verdi om brevkontektsen: Alltid, sak, vedtak

|prioritet
|Integer
|Inneholder verdi om rekkeføle/prioritering brevet har.

|===

Doksysbrev må inneholde følgende elementer i tillegg til elementene beskrevet over i <<index.adoc#brev-tabell,brev-tabellen>>:

.Doksysbrev
[cols="1,1,3",]
|===
|Element | Type | Beskrivelse

|dokumentmalId
|String
|Inneholder dokumentmalId som er en referanse til xsd'ene

|dokumentmalFelleselementId
|String
|Inneholder dokumentmalFelleselementId som er en refarnse til felleselement xsd'ene

|vedleggListe
|List<DoksysVedlegg>
|Inneholder en liste med doksysvedlegg som tilhører brevet.

|===

GammeltBrev (HPExstream brev) må inneholde følgende elementer i tillegg til elementene beskrevet over i <<index.adoc#brev-tabell,brev-tabellen>>:

|===
|Element | Type | Beskrivelse

|brevgruppe
|String
|Inneholder verdi om hvilke brevbruppe brevet tilhører.

|===

=== Hvordan legge inn nye brev

==== Teknisk

Brev er kategorisert som enten Doksysbrev eller "Gammeltbrev" (HPExstream osv.).
Alle brev er lagt inn i et Hashmap med brevkode som keyId og Brev som et objekt.

[source,java]
----
brevMap.put("OPPHOR_ENDRING_UT_BT",() ->
                new GammeltBrev("PE_UT_07_200",false, ... )

brevMap.put("AP_AVSL_ENDR", () ->
                new Doksysbrev("AP_AVSL_ENDR",true, ... )
----

For å legge inn et nytt brev må det legges inn en ny mapping i "brevMap" med informasjon om det nye brevet.
[TIP]
====
_Brevkode_, som er input til tjensten, kan både være av type T_K_BATCHBREV og T_K_BREV_T.

* _Brevkode_ er nøkkelen som brukes i brevmappet
* _brevkodeInBrevsystem_ er verdien som blir brukt til brevbestillinger
====

=== DoksysVedleggMapper

DoksysVedleggMapper er bygget opp likt som BrevdataMapper ved at alle vedleggene er lagt inn i et _hashmap_.
Vedleggene er knyttet til Brevdata med _vedleggkey_, hvor nøkkelen legges til Brevdata i den rekkefølgen vedleggene er ønsket.

.Brevdatamapper
----
brevMap.put("AP_INNV_AO_UT_AUTO", () ->
                new Doksysbrev("AP_INNV_AO_UT_AUTO",
                        false,
                        ...
                        "000086",
                        "00001",
                        doksysVedleggMapper
.map("RETTIGH_PLIKT_V1", "AP_MND_UTB_V1", "AP_OPPL_BER_V1", "AP_AVDOD_OPPL_BER_V1")));
----